@startuml rule-management-backend

autonumber 1

box "           //<<Container>>//\nRule Management Backend"
participant "Application" as app  <<Component>>
participant "Domain Services" as serv  <<Component>>
participant "Postgres" as postgres  <<Component>>
participant "AMQP" as amqp <<Component>>
participant "Domain" as dom <<Component>>
end box

participant "Rule Management\nDatabase" as db <<Container>>
participant "Message\nBroker" as MB <<Container>>

note over app : every 30 minutes

activate app
app -> serv ++ : activate all\n draft scenarios
serv -> postgres ++ : fetch draft\ncenarios
postgres -> db ++ : query draft scenarios
return scenarios
postgres -> dom ++ : map database model\nto domain model
return domain model
return scenarios
serv -> dom ++ : mark scenarios\nas active
return active scenarios
serv -> postgres ++ : update\n scenarios
postgres -> db ++ : update scenarios
return scenarios
postgres -> dom ++ : map database model\nto domain model
return domain model
return activated\nscenarios
return scenarios
alt list of scenarios isn't empty
app -> amqp ++-- : publish new active scenarios
amqp -> MB -- :publish scenarios
end
@enduml
