@startuml database

folder "sensae-console" {
    folder "project" {
        folder "databases" {
            folder "data-decoder-database"
            folder "data-processor-database"
            folder "device-management-database"
            folder "identity-management-database"
            folder "notification-management-database"
            folder "rule-management-database"
            folder "smart-irrigation-business-database"
        }
    }
}

@enduml
