@startuml frontend

left to right direction

skinparam groupInheritance 2

folder "sensae-console" {
    folder "project" {
        folder "frontend-services" {
            folder "apps" as a {
                folder "data-decoder-frontend" as a1
                folder "data-processor-frontend" as a2
                folder "device-management-frontend" as a3
                folder "identity-management-frontend" as a5
                folder "rule-management-frontend" as a7
                folder "ui-aggregator" as a9
            }
            folder "libs" as b {
                folder "data-decoder" as b1
                folder "data-processor" as b2
                folder "device-management" as b3
                folder "identity-management" as b5
                folder "rule-management" as b9
                folder "auth" as b7
                folder "core" as b8
            }   
            a1 ..> b1
            a2 ..> b2
            a3 ..> b3
            a5 ..> b5
            a7 ..> b9

            a9 ..> b7

            b1 ..> b7
            b1 ..> b8
            b2 ..> b7
            b2 ..> b8
            b3 ..> b7
            b3 ..> b8
            b5 ..> b7
            b5 ..> b8
            b9 ..> b7
            b9 ..> b8
        }
    }
}

@enduml
