@startuml complete

skinparam defaultFontSize 20
skinparam Monochrome true
skinparam sequenceMessageAlign center
skinparam componentStyle uml2
skinparam packageStyle rectangle

node "Sensae Console" <<Kubernetes>> {
    node "linux-n" <<node>> as SYSTEM1 {
        component "Sensae A Service"
        component "Sensae B Service"
        component "Sensae C Service"
    }
    node "linux-1" <<node>> as SYSTEMN {
        component "Sensae X Service"
        component "Sensae A Service" as A
    }
    SYSTEMN --- SYSTEM1 : http
    SYSTEMN --- SYSTEM1 : amqp
    SYSTEMN --- SYSTEM1 : sql
}

node "Helium" {
    node "Helium Console" <<External System>> as HC
}

node "Azure" {
    node "Azure Active Directory" <<External System>> as AAD
}

node "Google Cloud" {
    node "Google Identity Platform" <<External System>> as GIP
    node "Google Email Platform" <<External System>> as EMAIL
    GIP -[hidden]- EMAIL
}

node "Twilio Paltform" {
    node "SMS Service" <<External System>> as SMS
}

HC -- SYSTEM1 : http
HC - SYSTEMN : http
SYSTEM1 -- SMS : http

AAD -- SYSTEMN : http

SYSTEM1 - EMAIL : smtp
SYSTEMN - GIP: http

@enduml
