@startuml logical-view

skinparam Monochrome true
skinparam sequenceMessageAlign center
skinparam componentStyle uml2
skinparam packageStyle rectangle

[Sensae Console] as S <<System>>
component "Business Application [ i ]" as EXTER <<System>>

() "Sensae UI" as UI
() "Sensae Management\nAPI" as API
() "Sensae API for\nBusiness Application" as DATA_API
() "IoT Middleware\nDownlink\nRest API" as OUT_ENDPOINT
() "Sensae Console\nUplink\nRest API" as IN_ENDPOINT
() "Identity Provider\nOpenID Connect\nAPI" as OPEN_ID
() "Business Application UI" as EXTER_UI
() "Business Application\nAPI" as EXTER_API
() "SMS Dispatching\nService API" as SMS
() "Email Dispatching\nService API" as EMAIL

API -- S
UI -- S
EXTER_UI -- EXTER
EXTER_API -- EXTER
S - DATA_API
OPEN_ID )- S
S -- IN_ENDPOINT

S --( OUT_ENDPOINT

EXTER --( EMAIL
EXTER --( SMS

actor "Manager" as Manager
actor "Costumer" as Costumer
actor "Anonymous User" as Anonymous

Manager --( UI
Manager --( EXTER_UI
Costumer --( UI
Costumer --( EXTER_UI
Anonymous --( EXTER_UI

DATA_API )- EXTER

@enduml
