@startuml physical-view

skinparam defaultFontSize 20
skinparam Monochrome true
skinparam sequenceMessageAlign center
skinparam componentStyle uml2
skinparam packageStyle rectangle

node "Cloud" {
    node "Sensae Console" <<System>> as SYSTEM1
}

node "Helium" {
    node "Helium Console" <<External System>> as HC
}

node "Azure" {
    node "Azure Active Directory" <<External System>> as AAD
}

node "Google Cloud" {
    node "Google Identity Platform" <<External System>> as GIP
    node "Google Email Platform" <<External System>> as EMAIL
}

node "Twilio Paltform" {
    node "SMS Service" <<External System>> as SMS
}

SYSTEM1 -- HC : http
SYSTEM1 -- HC : http
EMAIL -- SYSTEM1 : smtp
SYSTEM1 -- SMS : http

AAD -- SYSTEM1 : http
GIP -- SYSTEM1 : http


@enduml
