@startuml physical-view-single-tenant

left to right direction

skinparam defaultFontSize 20
skinparam Monochrome true
skinparam sequenceMessageAlign center
skinparam componentStyle uml2
skinparam packageStyle rectangle

node "On-Permise / Cloud Linux VM Instance" <<Device>> {
    node "Sensae Console" <<System>> as SYSTEM1
    node "   <<Business Application>>\nWaste Management" <<System>> as SYSTEM2
    node "     <<Business Application>>\nFleet Management" <<System>> as SYSTEM4
}

node "On-Permise / Cloud\nLinux VM Instance" <<Device>> as D {
    node "   <<Business Application>>\nSmart Parking" <<System>> as SYSTEM3
}

SYSTEM1 -- SYSTEM2 : "<<protocol>>\namqp"
SYSTEM1 -- SYSTEM3 : "<<protocol>>\namqp"
SYSTEM1 -- SYSTEM4 : "<<protocol>>\namqp"

@enduml
