@startuml data-flow-scope

state "Data Relayer" as DataRelayer
state "Data Gateway" as DataGateway
state decoded_or_encoded <<choice>>
state "Data Processor Flow" as Processor
state "Data Store" as DataStore
state "Data Decoder Flow" as Decoder
state "Device Ownership" as Identity
state "Data Validator" as Validator
state "Device Management Flow" as Device
state "Alert Dispatcher" as Alert

DataStore: Data Unit is stored

DataRelayer : Any data received as the body
DataRelayer : of an HTTP POST is proxied

DataGateway : Data is wraped in a
DataGateway : Message Envelop with
DataGateway : specific routing keys

Processor : Data Unit is transformed according
Processor : to the defined mapper for the
Processor : type of device that sent the data

Decoder : Data Unit is transformed according
Decoder : to the defined script for the
Decoder : type of device that sent the data

Identity : Device ownership details are
Identity : added to the Data Unit

Device : Device information details
Device : are added to the Data Unit
Device : and sub device measures are 
Device : extracted to be reprocessed

Validator : Data Unit is examined 
Validator : to determine if
Validator : it is valid or not

Alert: Data Unit is analised and
Alert: alerts are produced
Alert: based on rules

[*] --> DataRelayer
DataRelayer -> DataGateway
DataGateway -> decoded_or_encoded
decoded_or_encoded --> Processor : decoded
decoded_or_encoded --> Decoder : encoded
Decoder --> Identity
Processor --> Identity

decoded_or_encoded -> DataStore : any 

Identity --> Device

Device -> Validator

Device ---> Identity : each sub device\nData Unit is processed

Validator --> Alert : if data is valid

@enduml
