@startuml message-envelop-model

left to right direction

hide empty members

abstract MessageEnvelop {
    oid : UUID
    hops : Number
}

class MessageConsumed {
    toSupplied(updateDataFunction, updateRoutingKeysFunction) : Optional<MessageSupplied> 
}

class MessageSupplied {
    {static} create(data, routingKeys) : MessageSupplied
    {static} from(messageConsumed, data, routingKeys) :  Optional<MessageSupplied>
}

interface RoutingKeys {
    
}

interface Information {

}

MessageEnvelop "1" --> "1" RoutingKeys : routingKeys
MessageEnvelop "1" --> "1" Information : information

MessageSupplied -|> MessageEnvelop
MessageEnvelop <|- MessageConsumed

@enduml
