@startuml message-envelop-model

hide empty members

abstract MessageEnvelop {
    oid : UUID
    hops : Number
}

class MessageConsumed {
    toSupplied(updateDataFunction, updateRoutingKeysFunction) : Optional<MessageSupplied> 
}

class MessageSupplied {
    {static} create(data, routingKeys) : MessageSupplied
    {static} from(messageConsumed, data, routingKeys) :  Optional<MessageSupplied>
}

interface RoutingKeys {
    
}

interface Information {

}

MessageEnvelop "1" -> "1" RoutingKeys : routingKeys
Information "1" <- "1" MessageEnvelop : information

MessageSupplied --|> MessageEnvelop
MessageEnvelop <|-- MessageConsumed

@enduml
