@startuml routing-model

hide empty members

interface "RoutingKey" as RoutingKey2 {
    details()
    key()
}

interface RoutingKeys {
    details()
    keys()
}

class AlertRoutingKeys {

}

class InternalRoutingKeys {

}

class CommandRoutingKeys {

}

class DataRoutingKeys {

}

class ChannelOptions {
    value: String
}

enum NH3DataOptions {
    UNIDENTIFIED_NH3_DATA
    WITH_NH3_DATA
    WITHOUT_NH3_DATA
}

enum ContainerTypeOptions {
    DATA_GATEWAY
    DATA_DECODER
    DATA_STORE
    SMART_IRRIGATION
    ...
    OTHER
}

enum RoutingKeysBuilderOptions {
    SUPPLIER
    CONSUMER
}

class ProtocolVersionOptions {
    majorVersion: Number
    minorVersion: Number
    patchVersion: Number
}

interface RoutingKeysBuilder {
    build() : Optional<RoutingKeys>
}

class AlertRoutingKeysBuilder {
}

class InternalRoutingKeysBuilder {
}

class CommandRoutingKeysBuilder {
}

class DataRoutingKeysBuilder {
}

class RoutingKeyOption<K extends RoutingKey> {
    isAny : Boolean
    routingKey : K
    details()
    key()
    {static} of( routingKey ) : RoutingKeyOption
    {static} any() : RoutingKeyOption
}

RoutingKeys <|-- AlertRoutingKeys
RoutingKeys <|-- InternalRoutingKeys
RoutingKeys <|-- CommandRoutingKeys
RoutingKeys <|-- DataRoutingKeys

RoutingKeysBuilder <|-- AlertRoutingKeysBuilder
RoutingKeysBuilder <|-- InternalRoutingKeysBuilder
RoutingKeysBuilder <|-- DataRoutingKeysBuilder
RoutingKeysBuilder <|-- CommandRoutingKeysBuilder

AlertRoutingKeys "1" --> "*" RoutingKeyOption

InternalRoutingKeys "1" --> "*" RoutingKeyOption
note on link: each one has different\ntypes of RoutingKeyOption

CommandRoutingKeys "1" --> "*" RoutingKeyOption
DataRoutingKeys "1" --> "*" RoutingKeyOption

DataRoutingKeysBuilder ..> DataRoutingKeys: creates
AlertRoutingKeysBuilder ..> AlertRoutingKeys: creates
InternalRoutingKeysBuilder ..> InternalRoutingKeys: creates
CommandRoutingKeysBuilder ..> CommandRoutingKeys: creates

ProtocolVersionOptions "1" <-- "1" RoutingKeysBuilder: protocolVersion
ContainerTypeOptions "1" <-- "1" RoutingKeysBuilder: containerType
RoutingKeysBuilderOptions "1" <-- "1" RoutingKeysBuilder: builderType

RoutingKey2 <|-- RoutingKeysBuilderOptions
RoutingKey2 <|-- ContainerTypeOptions
RoutingKey2 <|-- ProtocolVersionOptions
RoutingKey2 <|- ChannelOptions
NH3DataOptions -|> RoutingKey2

RoutingKeysBuilder -[hidden] RoutingKeys

@enduml
