@startuml rule-management-model

hide empty members

class RuleScenario {

}

class RuleScenarioId {
    value: UUID
}

class RuleScenarioName {
    value: String
}

class Script {

}

class ScriptContext {
    value: String
}

RuleScenario "1" -- "1" Script : has >
RuleScenario "1" - "1" RuleScenarioId : identified by >
RuleScenario "1" -- "1" RuleScenarioName : for >
Script "1" -- "1" ScriptContext : defined >

@enduml
