@startuml smart-irrigation-model-2

hide empty members

class IrrigationZone

class IrrigationZoneName

class Area

class IrrigationZoneId

class BoundaryVertex

class GPSPoint

class VertexPosition

Area "1" -- "*" BoundaryVertex: has boundaries >
IrrigationZone "1" -- "1" Area: defined by >
IrrigationZone "1" -- "1" IrrigationZoneName: named >
IrrigationZone "1" -- "1" IrrigationZoneId: identified by >

BoundaryVertex "1" -- "1" GPSPoint : at >
BoundaryVertex "1" -- "1" VertexPosition : numbered according to >

@enduml
