@startuml data-decoder-frontend

skinparam sequenceMessageAlign center
skinparam Shadowing false
skinparam componentStyle uml2
skinparam packageStyle rectangle

interface "UI" as COMP_API

component "Data Decoder Frontend" <<Container>> {

    folder "App" {
        component "Presentation" as COMP <<Component>>
    }
    interface "Services API" as SERV_API
    interface "Model API" as MOD_API

    folder "Library" {
        folder "Data Decoder" {
            component "DTOS" as DTO <<Component>>
            component "Mappers" as MAP <<Component>>
            component "Model" as MOD <<Component>>
            component "Services" as SERV <<Component>>

            interface "DTOs API" as DTO_API
            interface "Mappers API" as MAP_API
        }

        component "Auth" as AUTH <<Component>>
        component "Utils" as UTIL <<Component>>

        interface "Auth API" as AUTH_API
        interface "Utils API" as UTIL_API
    }

    COMP -( SERV_API

    COMP - COMP_API
    DTO_API -- DTO
    MAP_API -- MAP
    MOD_API -- MOD
    SERV_API -- SERV
    AUTH_API -- AUTH
    UTIL_API -- UTIL

    SERV --( DTO_API
    AUTH_API )- SERV
    SERV --( UTIL_API
    COMP --( MOD_API
    SERV --( MOD_API
    SERV --( MAP_API

    DTO_API )- MAP
    MOD_API )- MAP
}

@enduml
