@startuml data-gateway

interface "AMQP API" as AMQP_API
interface "REST API" as REST_API

component "Data Gateway" <<Container>> {
    component "Domain" as DOM <<Component>>
    component "Application" as APP <<Component>>
    folder "Infrastructure" as INFRA {
        folder "Endpoint" as ENDPOINT {
            component "AMQP" as AMQP <<Component>>
            component "REST" as REST <<Component>>
        }
    }
    interface "Application API" as APP_API
    interface "Domain API" as DOM_API

    DOM_API - DOM

    AMQP_API )-- AMQP
    REST_API -- REST
    APP_API - APP

    APP -( DOM_API
    AMQP --( APP_API
    REST --( APP_API
}

@enduml
