@startuml data-store

interface "AMQP API" as AMQP_API
interface "MongoDB API" as DB_API

component "Data Store" <<Container>> {
    component "Domain" as DOM <<Component>>
    component "Application" as APP <<Component>>
    folder "Infrastructure" as INFRA {
        folder "Persistence" {
            component "MongoDB" as DB <<Component>>
        }
        folder "Endpoint" as ENDPOINT {
            component "AMQP" as AMQP <<Component>>
        }
    }

    interface "Application API" as APP_API
    interface "Domain API" as DOM_API

    DOM_API - DOM

    AMQP_API )-- AMQP
    APP_API - APP
    DB_API )-- DB

    AMQP --( APP_API
    DB --( DOM_API
    DOM_API )- APP
}

@enduml
