@startuml data-decoder-frontend

skinparam sequenceMessageAlign center
skinparam Shadowing false
skinparam componentStyle uml2
skinparam packageStyle rectangle

interface "UI" as COMP_API

component "Data Decoder Frontend" {

    folder "App" {
        component "Presentation" as COMP
    }

    folder "Library" {
        component "DTOS" as DTO
        component "Mappers" as MAP
        component "Model" as MOD
        component "Services" as SERV
        component "Auth" as AUTH
        component "Utils" as UTIL

        interface "DTOs API" as DTO_API
        interface "Mappers API" as MAP_API
        interface "Model API" as MOD_API
        interface "Services API" as SERV_API
        interface "Auth API" as AUTH_API
        interface "Utils API" as UTIL_API
    }

    COMP --( SERV_API

    COMP - COMP_API
    DTO_API -- DTO
    MAP_API -- MAP
    MOD_API -- MOD
    SERV_API - SERV
    AUTH_API -- AUTH
    UTIL_API -- UTIL

    SERV --( DTO_API
    SERV --( AUTH_API
    SERV --( UTIL_API
    COMP --( MOD_API
    SERV --( MOD_API
    SERV --( MAP_API

    DTO_API )- MAP
    MOD_API )- MAP
}

@enduml
