@startuml data-store-backend

component "Data Store Backend" {
    component "Domain" as DOM
    component "Infrastructure" as INFRA {
        component "Boot" as BOOT
        component "Persistence" {
            component "MongoDB" as DB
            interface "MongoDB API" as DB_API
        }
        component "Endpoint" as ENDPOINT {
            component "AMQP" as AMQP
            interface "AMQP API" as AMQP_API
        }
        interface "Boot API" as BOOT_API
    }

    interface "Domain API" as DOM_API

    DOM_API - DOM

    AMQP_API -- AMQP
    DB_API -- DB

    BOOT_API - BOOT

    AMQP --( DOM_API
    DB --( DOM_API
    BOOT --( DB_API
    BOOT --( AMQP_API
}

@enduml
