@startuml device-commander

'left to right direction

interface "AMQP API" as INGRESS_API
interface "REST API" as REST_API

component "Device Ownership" <<Container>> {
    component "Domain" as DOM <<Component>>
    component "Application" as APP <<Component>>
    folder "Infrastructure" as INFRA {
        folder "Endpoint" as ENDPOINT {
            folder "AMQP" as AMQP {
                component "Ingress" as INGRESS <<Component>>
                component "Internal" as INTERNAL <<Component>>
            }
            component "REST" as REST <<Component>>
        }
    }

    interface "Domain API" as DOM_API
    interface "Application API" as APP_API

    DOM_API - DOM
    APP_API - APP
    REST_API )-- REST

    INGRESS_API )-- INGRESS
    INGRESS_API )-- INTERNAL

    APP - DOM_API
    INGRESS --( APP_API
    INTERNAL --( APP_API
    REST --( APP_API
}

@enduml
