@startuml device-ownership-backend

interface "AMQP API" as AMQP_API

component "Device Ownership Backend" <<Container>> {
    component "Application" as APP <<Component>>
    component "Domain" as DOM <<Component>>
    folder "Infrastructure" as INFRA {
        folder "Endpoint" as ENDPOINT {
            folder "AMQP" as AMQP {
                component "Egress" as EGRESS <<Component>>
                component "Ingress" as INGRESS <<Component>>
                component "Internal" as INTERNAL <<Component>>
            }
        }
        folder "Persistence" as PRESIST {
            component "Memory" as MEM <<Component>>
        }
    }

    interface "Application API" as APP_API
    interface "Domain API" as DOM_API

    DOM_API - DOM

    AMQP_API )-- EGRESS
    AMQP_API )-- INGRESS
    AMQP_API )-- INTERNAL

    APP_API - APP

    EGRESS --( APP_API
    INGRESS --( APP_API
    INTERNAL --( APP_API
    APP -( DOM_API
    MEM -( DOM_API
}

@enduml
