@startuml device-commander

interface "Boot API" as BOOT_API

component "Device Ownership" {
    component "Domain" as DOM
    component "Application" as APP
    folder "Infrastructure" as INFRA {
        component "Boot" as BOOT
        folder "Endpoint" as ENDPOINT {
            folder "AMQP" as AMQP {
                component "Ingress" as INGRESS
                component "Internal" as INTERNAL
                interface "Ingress API" as INGRESS_API
                interface "Internal API" as INTERNAL_API
            }
            component "REST" as REST
            interface "REST API" as REST_API
        }
    }

    interface "Domain API" as DOM_API
    interface "Application API" as APP_API

    DOM_API - DOM
    APP_API - APP
    REST_API -- REST

    INGRESS_API -- INGRESS
    INTERNAL_API -- INTERNAL

    BOOT_API - BOOT
    APP - DOM_API
    INGRESS --( APP_API
    INTERNAL --( APP_API
    REST --( APP_API
    BOOT --( INTERNAL_API
    BOOT --( INGRESS_API
    BOOT --( REST_API
}

@enduml
