@startuml device-ownership-backend

interface "Boot API" as BOOT_API

component "Device Ownership Backend" {
    component "Application" as APP
    component "Domain" as DOM
    folder "Infrastructure" as INFRA {
        component "Boot" as BOOT
        folder "Endpoint" as ENDPOINT {
            folder "AMQP" as AMQP {
                component "Egress" as EGRESS
                component "Ingress" as INGRESS
                component "Internal" as INTERNAL
                interface "Egress API" as EGRESS_API
                interface "Ingress API" as INGRESS_API
                interface "Internal API" as INTERNAL_API
            }
        }
        folder "Persistence" as PRESIST {
            component "Memory" as MEM
            interface "Memory API" as MEM_API
        }
    }

    interface "Application API" as APP_API
    interface "Domain API" as DOM_API

    DOM_API - DOM

    MEM_API -- MEM

    EGRESS_API -- EGRESS
    INGRESS_API -- INGRESS
    INTERNAL_API -- INTERNAL

    APP_API - APP
    BOOT_API - BOOT

    EGRESS --( APP_API
    INGRESS --( APP_API
    INTERNAL --( APP_API
    APP -( DOM_API
    MEM -( DOM_API
    BOOT --( INTERNAL_API
    BOOT --( EGRESS_API
    BOOT --( INGRESS_API
    BOOT --( MEM_API
}

@enduml
