@startuml notification-dispatcher-backend

interface "AMQP API" as AMQP_API
interface "SMS API" as SMS_API
interface "EMAIL API" as EMAIL_API

component "Notification Dispatcher Backend" <<Container>> {
    component "Domain" as DOM <<Component>>
    component "Application" as APP <<Component>>
    folder "Infrastructure" as INFRA {
        folder "Endpoint" as ENDPOINT {
            component "AMQP" as AMQP <<Component>>
            component "SMS" as SMS <<Component>>
            component "EMAIL" as EMAIL <<Component>>
        }
        folder "Persistence" as PERS {
            component "Memory" as MEM <<Component>>
        }
    }
    interface "Application API" as APP_API
    interface "Domain API" as DOM_API

    MEM -( DOM_API

    DOM_API - DOM
    APP_API - APP

    AMQP_API )-- AMQP
    SMS_API )-- SMS
    EMAIL_API )-- EMAIL

    AMQP --( APP_API
    SMS --( APP_API
    EMAIL --( APP_API
    APP -( DOM_API
}

@enduml
