@startuml smart-irrigation-backend

interface "QuestDB API" as QUEST_API
interface "Postgres API" as POSTG_API

interface "Graphql API" as GRAPH_API
interface "AMQP API" as AMQP_API

component "Smart Irrigation Backend" <<Container>> {
    component "Application" as APP <<Component>>
    component "Domain" as DOM <<Component>>
    component "Domain Services" as DOM_SERV <<Component>>
    folder "Infrastructure" as INFRA {
        folder "Endpoint" as ENDPOINT {
            component "Graphql" as GRAPH <<Component>>
            component "AMQP" as AMQP <<Component>>
        }
        folder "Presistence" as PERSIST {
            component "Postgres" as POSTG <<Component>>
            component "QuestDB" as QUEST <<Component>>
        }
    }

    interface "Application API" as APP_API
    interface "Domain API" as DOM_API
    interface "Domain Services API" as DOM_SERV_API

    GRAPH_API -- GRAPH
    DOM_API -- DOM
    DOM_SERV_API -- DOM_SERV

    POSTG_API )-- POSTG
    QUEST_API )-- QUEST
    AMQP_API )-- AMQP
    APP_API -- APP

    AMQP --( APP_API
    POSTG --( DOM_API
    QUEST --( DOM_API
    GRAPH --( APP_API
    DOM_SERV_API )-- APP
    DOM_API )-- DOM_SERV
}

@enduml
