@startuml scopes

skinparam componentStyle rectangle

actor Manager

actor "Costumer or\nAnonymous User" as User

collections "IoT Middlewares" as ExternalSystem

component "Sensae Console"<<System>> {

    component "Configuration\nScope" as Configuration

    component "Data Flow\nScope" as DataFlow
}

component "Business Applications\nScope" as Service

ExternalSystem -> DataFlow : feeds device uplinks
ExternalSystem <- DataFlow : feeds device downlinks

Configuration --> DataFlow : defines the\nbehaviour of
Configuration <-- DataFlow : informs about\nnotable\noccurrences

Service <-- DataFlow : feeds sanitized data\nand alerts
Service --> DataFlow : dispatches\ncommands

Manager --> Configuration : configures\nthe ETL

User --> Service : interacts with the\nsevices available

@enduml
