@startuml scopes

skinparam componentStyle rectangle

actor Manager

actor "Costumer or\nAnonymous User" as User

collections "External\nSystems" as ExternalSystem

component "Sensae Console"<<System>> {

    component "Configuration\nScope" as Configuration

    component "Data Flow\nScope" as DataFlow

    component "Services\nScope" as Service
}

ExternalSystem -> DataFlow : feeds unsanitized\ndata to

Configuration --> DataFlow : defines the\nbehaviour of
Configuration <-- DataFlow : informs about\nnotable\noccurrences

DataFlow -> Service : feeds sanitized data\nand alerts to
Service -> DataFlow : sends commands to

Manager --> Configuration : configures\nthe ETL

User ---> Service : interacts with the\nsevices available

@enduml
