@startuml consult-data-processor

autonumber 1.1

skinparam style strictuml

participant "Data Processor Frontend" as FRONT <<Container>>
participant "Data Processor Backend" as BACK <<Container>>
participant "Data Processor Database" as DB <<Container>>

FRONT -> BACK ++ : request data mappers
BACK -> BACK: verifies if the\ntoken is valid
BACK -> BACK: verifies if the\nuser has the\nneeded permissions
BACK -> DB ++: query data mappers
return data mappers
return data mappers

@enduml
