@startuml container-ready

autonumber 1.1

skinparam style strictuml

participant "Alert Dispatcher\nBackend" as ALERT <<Container>>
participant "Message\nBroker" as MB <<Container>>
participant "Rule Management\nBackend" as RULE <<Container>>
participant "Rule Management\nDatabase" as RULE_DB <<Container>>

activate MB

activate ALERT
ALERT -> MB : publishes a "initialized rule\nmanagement concern" message 
deactivate ALERT
autonumber inc A
MB -> RULE : notifies about the message
activate RULE
RULE -> RULE_DB : requests all active rules
activate RULE_DB
RULE_DB --> RULE : returns all rules
deactivate RULE_DB
RULE -> RULE : computes the current\nrule management state
RULE -> MB : publishes a "sync rule\nmanagement concern" message
deactivate RULE
autonumber inc A
MB -> ALERT : notifies about the message
activate ALERT
ALERT -> ALERT : stores the\nrule management\nstate internally
ALERT -> MB : unsubscribes from\n"sync rule management concern"
deactivate ALERT

@enduml
