@startuml data-decoder-flow-2

autonumber 1.1

skinparam style strictuml

participant "Data Decoder\nFlow Backend" as DECODER_FLOW <<Container>>
participant "Message\nBroker" as MB <<Container>>

activate MB

-> MB : publishes a message containing a decoder\ndetails @ Internal Topic

autonumber inc A
MB -> DECODER_FLOW : notifies the message @ Internal Topic
activate DECODER_FLOW
DECODER_FLOW -> DECODER_FLOW : stores the data decoder of that device type\nfor a defined amount of hours
DECODER_FLOW -> DECODER_FLOW : retrieves stored data units of that device type

loop for each data unit found
    DECODER_FLOW -> DECODER_FLOW : decodes the data unit
    DECODER_FLOW -> MB : publishes the processed data\nunit @ Data Topic

    autonumber inc A
    MB ->? :  notifies the message\n@ Data Topic

end
autonumber 2.6
DECODER_FLOW -> MB : publishes a "ping data decoder"\n message of the device type\n@ Internal Topic

autonumber inc A
autonumber inc A
MB ->? : notifies the message\n@ Internal Topic

@enduml
