@startuml device-live-location

skinparam sequenceMessageAlign center
skinparam style strictuml
autonumber 1.1
actor User

box "     //<<System>>//\nExternal Service"
participant "Fleet Management\nFrontend" as FRONT <<Container>>
participant "Fleet Management\nBackend" as BACK <<Container>>
participant "Fleet Management\nDatabase" as DB <<Container>>
end box

participant "Sensae Console" as MB <<System>>

activate User
User -> FRONT ++ : accesses page
FRONT -> BACK ++ : susbcribe to new\ndevice readings
BACK -> BACK : extracts user\ndomains from token
BACK -> BACK : open subscription for\nnew device readings
return subscription
FRONT -> FRONT : stores subscription
FRONT -> BACK ++ : fetch latest device readings
BACK -> BACK : extracts user\ndomains from token
BACK -> DB ++ : fetch latest device readings\nrelated to user domains
return latest devices readings
return latest devices readings
FRONT --> User: presents latest\ndevices readings
... after some time ...
autonumber inc A
MB -> BACK ++ : notifies about new device readings
activate MB
deactivate MB 
BACK -> DB ++ : store device readings
return success
BACK -> BACK : search for active\nsubscriptions that can see\nthe new device readings
BACK -> FRONT : new device readings
deactivate BACK
FRONT -> FRONT : replace latest device\nreadings with new one
FRONT --> User : show new\ndevice readings
... after some time ...
autonumber inc A
User -> FRONT : leaves the page
FRONT -> BACK : unsubscribe from\nsubscription
activate BACK
BACK -> BACK : close subscription
BACK --> FRONT : subscription closed
deactivate BACK
FRONT -> FRONT : remove subscription

@enduml
