@startuml edit-device-management

autonumber 1.1

skinparam style strictuml

participant "Device Management\nFrontend" as FRONT <<Container>>
participant "Device Management\nBackend" as BACK <<Container>>
participant "Device Management\nDatabase" as DB <<Container>>
participant "Message\nBroker" as MB <<Container>>

activate FRONT
FRONT -> BACK ++ : device\ninformation update
BACK -> BACK: verifies if the\ntoken is valid
BACK -> BACK: verifies if the\nuser has the\nneeded permissions
BACK -> BACK : verify if user\nowns the device
BACK -> DB ++: store changes made to\ndevice information
return updated\ndevice information
BACK -> MB : publish that the device was updated\n@ Internal Topic
activate MB
deactivate MB
return updated\ndevice information

@enduml
