@startuml notification-dispatch

skinparam sequenceMessageAlign center
skinparam style strictuml
autonumber 1.1
actor User

box "Sensae Console"
participant "Notification Management\nFrontend" as FRONT
participant "Notification Management\nBackend" as BACK
participant "Notification Dispatcher\nBackend" as DISP
participant "Notification Management\nDatabase" as DB
participant "Message\nBroker" as MB
end box

interface "SMS Dispatcher" as EMAIL
interface "Email Dispatcher" as SMS

activate MB 

User -> FRONT ++ : access page

... after some time ...
autonumber inc A

?-> MB : publishes a new alert

autonumber inc A
MB -> BACK ++ : notifies about the new alert

BACK -> BACK : transform alert\ninto notification

BACK -> DB ++ : store notification
return success

BACK -> BACK : search for active\nsubscriptions to the\ncontent type of the alert
BACK -> FRONT -- : notification
FRONT -> User : present notification

autonumber inc A
MB -> DISP ++ : notifies about the new alert

DISP -> DISP : search for addresses\nsubscribed to the content\n type of the alert via email

loop for each addressee

DISP -> DISP : collect addresse\n emails

DISP -> EMAIL ++ : request notification delivery via email

deactivate EMAIL 

end

DISP -> DISP : search for addresses\nsubscribed to the content\n type of the alert via sms

loop for each addressee

DISP -> DISP : collect addresse\nphone number

DISP -> SMS ++ : request notification delivery via sms

deactivate SMS

end

@enduml
