@startuml smart-irrigation

autonumber 1.1

skinparam style strictuml

box "     //<<System>>//\nSmart Irrigation"
participant "Smart Irrigation\nBackend" as BACK <<Container>>
participant "Smart Irrigation\nBusiness Database" as DB <<Container>>
end box

participant "IoT Middleware" as HC <<System>>

box "     //<<System>>//\nSensae Console"
participant "Message\nBroker" as MB <<Container>>
participant "Device Commander\nBackend" as COMM <<Container>>
end box 

MB <-? : publish\nalert
activate MB

MB -> BACK ++ : notify about new alert
deactivate MB

BACK -> BACK : extract related\ndevice from alert

BACK -> DB ++ : query device\ninformation

DB --> BACK -- : device information

alt device is not a valve
    BACK -> BACK : extract location\nfrom device
    BACK -> DB ++ : fetch device's\nirrigation zone
    return irrigation zone
    BACK -> DB ++ : fetch irrigation zone devices
    return devices information
    BACK -> BACK : search for irrigation\nzone's valve
end

BACK -> BACK : create command\nfor device
BACK -> MB -- : publish command
activate MB

autonumber inc A
MB -> COMM ++ : notify about\nnew command
deactivate MB

COMM -> COMM : search for device\ncommand details
COMM -> HC ++--: send http downlink
deactivate HC

@enduml
