@startuml alternative1

skinparam sequenceMessageAlign center
skinparam Shadowing false
skinparam componentStyle uml2
skinparam packageStyle rectangle

component "X Concern Frontend" as FRONT
component "X Concern Backend" as BACK
component "X Concern Database" as DB
component "Message Broker" as MB
component "X Concern Flow" as FLOW

interface "Message\nBroker API" as MB_API
interface "X Concern\nDatabase API" as DB_API
interface "X Concern\nBackend API" as BACK_API
interface "X Concern UI" as FRONT_API

MB -- MB_API
DB_API - DB
BACK_API -- BACK
FRONT - FRONT_API

BACK_API )- FRONT
BACK --( DB_API
MB_API )- FLOW
FLOW --( DB_API

@enduml
