@startuml alternative2

skinparam sequenceMessageAlign center
skinparam Shadowing false
skinparam componentStyle uml2
skinparam packageStyle rectangle

component "X Context Frontend" as FRONT
component "X Context Backend" as BACK
component "X Context Database" as DB
component "Message Broker" as MB
component "X Context Flow" as FLOW

interface "Message\nBroker API" as MB_API
interface "X Context\nDatabase API" as DB_API
interface "X Context\nBackend API" as BACK_API
interface "X Context Internal\nBackend API" as BACK_API_INT
interface "X Context UI" as FRONT_API

MB -- MB_API
DB_API - DB
BACK_API -- BACK
BACK_API_INT - BACK
FRONT - FRONT_API

BACK_API )- FRONT
BACK --( DB_API
MB_API )- FLOW
FLOW -( BACK_API_INT

@enduml
