@startuml alternative1

skinparam sequenceMessageAlign center
skinparam style strictuml
autonumber 1
!pragma teoz true

actor User

participant "Ui Aggregator" as AGGRE <<Container>>
participant "X Content\nFrontend" as XFRONT <<Container>>

participant "X Content\nBackend" as XBACK <<Container>>

participant "Internal\nAutentication Server" as AUTHSERVER <<Container>>

activate AGGRE
activate User

User -> AGGRE: Accesses the website
AGGRE --> User: Presents a\nSign In/Sign Up section
User -> AGGRE: Picks the Sign Up option
AGGRE --> User: Requests user infromation
User -> AGGRE: Provides information
AGGRE -> AGGRE: Provides information\nabout new User
AGGRE -> AUTHSERVER: Provides information\nabout new User
activate AUTHSERVER
AUTHSERVER -> AUTHSERVER: Performs user\nauthentication
AUTHSERVER --> AGGRE: Provides the access token
deactivate AUTHSERVER
AGGRE -> AGGRE: Notifies that a new\naccess token is present
AGGRE -> AGGRE: Checks what Frontends\nthe access token\ngives access to
AGGRE --> User: Presents\nX Content Frontend
User -> XFRONT: Accessses the service window
activate XFRONT
XFRONT --> User: Presents X interaction with the service
User -> XFRONT: Picks X interaction
XFRONT -> AGGRE: Requests the\naccess token
AGGRE -> AGGRE: Verifies if the\naccess token\nis still valid
AGGRE --> XFRONT: Provides the\naccess token
XFRONT -> XBACK: Requests infromation\nwith access token
activate XBACK
XBACK -> XBACK: Verifies user\nauthorization
XBACK --> XFRONT: Provides the information
deactivate XBACK
XFRONT --> User: Provides the information
@enduml
