@startuml device-ownership-backend

folder "device-ownership-backend" {
    folder "application" as APP
    folder "domain" as DOM
    folder "infrastructure" as INFRA {
        folder "endpoint" as ENDPOINT {
            folder "amqp" as AMQP {
                folder "egress" as EGRESS
                folder "ingress" as INGRESS
                folder "internal" as INTERNAL
            }
        }
        folder "persistence" as PERS {
            folder "memory" as MEM
        }
    }

    EGRESS ..> APP
    INGRESS ..> APP
    INTERNAL ..> APP
    APP .> DOM
    MEM ..> DOM
}

@enduml
