@startuml complete

skinparam sequenceMessageAlign center
skinparam Shadowing false
skinparam componentStyle uml2
skinparam packageStyle rectangle

interface "UI" as UI

interface "Sensae Console\nUplink\nRest API" as IN_ENDPOINT
interface "IoT Middleware\nDownlink\nRest API" as OUT_ENDPOINT

interface "Twilio SMS\nDisptacher API" as SMS_ENDPOINT
interface "SMTP Server" as SMTP_ENDPOINT

interface "OpenID Connect\nAPI" as AUTH_ENDPOINT

component "Sensae Console" <<System>> {
    component "UI Aggregator" as UIAG <<Container>>
    component "Fleet Management Frontend" as LTF <<Container>>
    component "Smart Irrigation Frontend" as SIF <<Container>>
    component "Device Management Frontend" as DRF <<Container>>
    component "Data Processor Frontend" as DPF <<Container>>
    component "Data Decoder Frontend" as DDF <<Container>>
    component "Identity Management Frontend" as IAMF <<Container>>
    component "Rule Management Frontend" as RULE_MAN_FRONT <<Container>>
    component "Notification Management Frontend" as NOTIF_MAN_FRONT <<Container>>

    interface "Fleet Management UI" as LTF_API
    interface "Smart Irrigation UI" as SIF_API
    interface "Device Management UI" as DRF_API
    interface "Data Processor UI" as DPF_API
    interface "Data Decoder UI" as DDF_API
    interface "Identity Management UI" as IAMF_API
    interface "Rule Management UI" as RULE_MAN_FRONT_API
    interface "Notification Management UI" as NOTIF_MAN_FRONT_API

    LTF_API -- LTF
    SIF_API -- SIF
    DRF_API -- DRF
    DPF_API -- DPF
    DDF_API -- DDF
    IAMF_API -- IAMF
    RULE_MAN_FRONT_API -- RULE_MAN_FRONT
    NOTIF_MAN_FRONT_API -- NOTIF_MAN_FRONT

    UIAG --( LTF_API
    UIAG --( SIF_API
    UIAG --( DRF_API
    UIAG --( DPF_API
    UIAG --( DDF_API
    UIAG --( IAMF_API
    UIAG --( RULE_MAN_FRONT_API
    UIAG --( NOTIF_MAN_FRONT_API

    component "Message\nBroker" as MB <<Container>>

    component "Fleet Management\nBackend" as LTB <<Container>>
    component "Smart Irrigation\nBackend" as SIB <<Container>>
    component "Device Management\nBackend" as DRB <<Container>>
    component "Device Management\nFlow Backend" as DRSB <<Container>>
    component "Data Gateway\nBackend" as DDG <<Container>>
    component "Data Relayer" as DR <<Container>>
    component "Data Processor\nFlow Backend" as DPSB <<Container>>
    component "Data Processor\nBackend" as DPB <<Container>>
    component "Data Decoder\nFlow Backend" as DDSB <<Container>>
    component "Data Decoder\nBackend" as DDB <<Container>>
    component "Data Validator\nBackend" as DVB <<Container>>
    component "Device Management\nDatabase" as DRDB <<Container>>
    component "Data Processor\nDatabase" as DPDB <<Container>>
    component "Data Decoder\nDatabase" as DDDB <<Container>>
    component "Identity Management\nDatabase" as IAMDB <<Container>>
    component "Data Store\nBackend" as DS <<Container>>
    component "Fleet Management\nDatabase" as QUESTDB <<Container>>
    component "Data Store\nDatabase" as MONGODB <<Container>>
    component "Smart Irrigation\nData Database" as SIDDB <<Container>>
    component "Smart Irrigation\nBusiness Database" as SIBDB <<Container>>
    component "Identity Management\nBackend" as IAMB <<Container>>
    component "Device Ownership\nBackend" as IAMSB <<Container>>
    component "Device Commander\nBackend" as DCB <<Container>>

    component "Rule Management\nBackend" as RULE_MAN_BACK <<Container>>
    component "Rule Management\nDatabase" as RULE_MAN_DB <<Container>>
    component "Alert Dispatcher\nBackend" as ALERT_BACK <<Container>>

    component "Notification Management\nBackend" as NOTIF_MAN_BACK <<Container>>
    component "Notification Management\nDatabase" as NOTIF_MAN_DB <<Container>>
    component "Notification Dispatcher\nBackend" as NOTIF_BACK <<Container>>

    interface "Message\nBroker API" as MB_API
    interface "Fleet Management\nBackend API" as LTB_API
    interface "Smart Irrigation\nBackend API" as SIB_API
    interface "Device Management\nBackend API" as DRB_API
    interface "Data Processor\nBackend API" as DPB_API
    interface "Data Decoder\nBackend API" as DDMB_API
    interface "Device Management\nDatabase API" as DRDB_API
    interface "Data Processor\nDatabase API" as DPDB_API
    interface "Data Decoder\nDatabase API" as DDDB_API
    interface "Identity Management\nDatabase API" as IAMDB_API
    interface "Fleet Management\nDatabase API" as QUESTDB_API
    interface "Data Store\nDatabase API" as MONGODB_API
    interface "Smart Irrigation Data\nDatabase API" as SIDDB_API
    interface "Smart Irrigation Business\nDatabase API" as SIBDB_API
    interface "Data Gateway\nBackend API" as DDG_API
    interface "Identity Management\nBackend API" as IAMB_API
    interface "Rule Management\nBackend API" as RULE_MAN_BACK_API
    interface "Rule Management\nDatabase API" as RULE_MAN_DB_API
    interface "Notification Management\nBackend API" as NOTIF_MAN_BACK_API
    interface "Notification Management\nDatabase API" as NOTIF_MAN_DB_API

    LTB --( QUESTDB_API
    RULE_MAN_BACK --( RULE_MAN_DB_API
    NOTIF_MAN_BACK --( NOTIF_MAN_DB_API
    SIB --( SIDDB_API
    SIB --( SIBDB_API
    DS --( MONGODB_API
    DDG -- DDG_API
    DPB_API -- DPB
    DDMB_API -- DDB
    DRB_API -- DRB
    MB_API --- MB
    DRDB_API -- DRDB
    DPDB_API -- DPDB
    DDDB_API -- DDDB
    IAMDB_API -- IAMDB
    RULE_MAN_BACK_API -- RULE_MAN_BACK
    NOTIF_MAN_BACK_API -- NOTIF_MAN_BACK
    LTB_API -- LTB
    SIB_API -- SIB
    IAMB_API -- IAMB
    UI -- UIAG
    MONGODB_API - MONGODB
    QUESTDB_API -- QUESTDB
    RULE_MAN_DB_API -- RULE_MAN_DB
    NOTIF_MAN_DB_API -- NOTIF_MAN_DB
    SIDDB_API -- SIDDB
    SIBDB_API -- SIBDB
    DRB --( DRDB_API
    DRDB_API )-[hidden]- DRSB
    DPB --( DPDB_API
    DDB --( DDDB_API
    DPDB_API )-[hidden]- DPSB
    DDDB_API )-[hidden]- DDSB
    IAMB --( IAMDB_API
    IAMDB_API )-[hidden]- IAMSB
    LTF --( LTB_API
    SIF --( SIB_API
    DPF --( DPB_API
    DDF --( DDMB_API
    DRF --( DRB_API
    IAMF --( IAMB_API
    RULE_MAN_FRONT --( RULE_MAN_BACK_API
    NOTIF_MAN_FRONT --( NOTIF_MAN_BACK_API

    LTB ---( MB_API
    SIB ---( MB_API
    DRB ---( MB_API
    DPB ---( MB_API
    DDB ---( MB_API
    IAMB ---( MB_API
    RULE_MAN_BACK ---( MB_API
    NOTIF_MAN_BACK ---( MB_API
    MB_API )--- DS
    MB_API )--- DDG
    MB_API )--- DVB
    MB_API )--- DRSB
    MB_API )--- DPSB
    MB_API )--- DDSB
    MB_API )--- IAMSB
    MB_API )--- DCB
    MB_API )--- ALERT_BACK
    MB_API )--- NOTIF_BACK

    DR -- IN_ENDPOINT
    DDG_API )- DR
    DCB ---( OUT_ENDPOINT
    IAMF --( AUTH_ENDPOINT
    AUTH_ENDPOINT )-- IAMB

    NOTIF_BACK ---( SMS_ENDPOINT
    NOTIF_BACK ---( SMTP_ENDPOINT

}

@enduml
