@startuml data-decoder-context

interface "Data Decoder UI" as FRONT_API
interface "Data Decoder\nBackend API" as BACK_API

component "Data Decoder" <<Context>> {
    component "Data Decoder\nBackend" <<Container>> as BACK
    component "Data Decoder\nFrontend" <<Container>> as FRONT
    component "Data Decoder\nDatabase" <<Container>> as DB

    interface "Data Decoder\nDatabase API" as DB_API

    DB_API -- DB
    FRONT_API -- FRONT
    BACK_API -- BACK
    DB_API )- BACK
    FRONT --( BACK_API

    component "Data Decoder\nData Flow" <<Container>> as FLOW #ebdc78
}

component "Message Broker" <<Container>> as MB
interface "Message Broker\nAPI" as MB_API

MB_API - MB

BACK --( MB_API

MB_API )-- FLOW

DB -[hidden]- FLOW

@enduml
