@startuml fleet-management-context

interface "Fleet Management UI" as FRONT_API
interface "Fleet Management\nBackend API" as BACK_API

component "Fleet Management" <<Context>> {
    component "Fleet Management\nBackend" <<Container>> as BACK
    component "Fleet Management\nFrontend" <<Container>> as FRONT
    component "Fleet Management\nDatabase" <<Container>> as DB

    interface "Fleet Management\nDatabase API" as DB_API

    DB - DB_API
    FRONT_API -- FRONT
    BACK_API -- BACK
    BACK --( DB_API
    FRONT --( BACK_API

}

component "Sensae Console" <<System>> as MB
interface "Sensae API for\nExternal Services" as MB_API

MB_API - MB

BACK -( MB_API

@enduml
