@startuml notification-management-context

interface "Notification Management UI" as FRONT_API
interface "Notification Management\nBackend API" as BACK_API

component "Notification Management" <<Context>> {
    component "Notification Management\nBackend" <<Container>> as BACK
    component "Notification Management\nFrontend" <<Container>> as FRONT
    component "Notification Management\nDatabase" <<Container>> as DB

    interface "Notification\nManagement\n Database API" as DB_API
    
    component "Notification Dispatcher\nBackend" <<Container>> as DISP

    DB_API -- DB
    FRONT_API -- FRONT
    BACK_API -- BACK
    DB_API )- BACK
    FRONT --( BACK_API
}

component "Message Broker" <<Container>> as MB
interface "Message\nBroker API" as MB_API

interface "SMS Dispatcher\nAPI" as SMS
interface "Email Dispatcher\nAPI" as EMAIL

MB_API - MB

BACK --( MB_API
DISP -( MB_API

BACK -[hidden]- DISP

DISP --( EMAIL
DISP --( SMS

@enduml
